### ISSUE TITLE
class variable accessed outside the class scope

### ISSUE THREAD

**Issue by srichakradhar** [abhi11210646/Image-search-google#1]
**cause:** getOptions accessing this.cseId from outside the imageSearch class

TypeError: Cannot read property 'cseId' of undefined
    at getOptions (/home/ubuntu/workspace/image_searchak/node_modules/image-search-google/lib/image-search.js:39:17)

**fix:** move getOptions inside the imageSearch class

**Comment by abhi11210646** [comment]
getOptions function is meant to accessed by search function internally. And not in the user code. How did you manage to access getoptions function??

**Comment by abhi11210646** [comment]
Variable scoping issue is fixed. Update your package, which is @1.0.6

**Comment by abhi11210646** [comment]
Did the issue resolved? @1.07
