### ISSUE TITLE
There are no advanced options on the search engine page

### ISSUE THREAD

**Issue by ghost** [abhi11210646/Image-search-google#5]
The instruction says:
`Do not specify any sites to search but instead use the "Restrict Pages using Schema.org Types" under the "Advanced options".`

https://cse.google.com/cse/create/new

But I cannot see 'advanced options' there. It requires to fill 'Sites to search'.

**Comment by abhi11210646** [comment]
Hi, @Sentero-esp12 you are welcome to make changes and raise a pull request.

**Comment by doverradio** [comment]
facing the same issue. if you go there, no advanced options are showing.

**Comment by Mar0xy** [comment]
> facing the same issue. if you go there, no advanced options are showing.

You have to create one first before you can see the option

**Comment by rafaelsouzaf** [comment]
Some instructions:

- In "https://cse.google.com/cse/create/new" add any website URL and save.
- Edit and remove the URL you added in the first step.
- Enable the option "Image Search"
- Enable the option "Search the entire web"
- Set the "Restrict Pages using Schema.org Types" as "Thing" or "Person" or any other.
